version: "3.4"

services:

  neo-postgres:
    image: postgres:12-alpine
    hostname: neo-postgres
    container_name: neo-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  neo-scan:
    hostname: neo-scan
    container_name: neo-scan
    depends_on:
      - neo-postgres
      - neo-consensus
    environment:
      DB_DATABASE: neoscan_prodv
      DB_HOSTNAME: neo-postgres
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      NEO_SEEDS: >-
        http://neo-consensus:30333
      PORT: 4000
      REPLACE_OS_VARS: 'true'
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 20s
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/4000
      timeout: 10s
    image: cityofzion/neoscan:latest
    labels:
      autoheal: 'true'
    ports:
      - 4000:4000
    restart: always

  neo-consensus:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: axlabs/neo-privatenet-openwallet-docker:latest
    hostname: neo-consensus
    container_name: neo-consensus
    ports:
      - 30333:30333
      - 30334:30334
      - 30335:30334
      - 30336:30334

  neo-python1:
    image: cityofzion/neo-python:v0.8.4
    hostname: neo-python1
    container_name: neo-python1
    tty: true
    volumes:
      - ./scripts/protocol.privnet-python.json:/neo-python/neo/data/protocol.privnet.json
    ports:
      - 30341:20332

  neo-python2:
    image: cityofzion/neo-python:v0.8.4
    hostname: neo-python2
    container_name: neo-python2
    tty: true
    volumes:
      - ./scripts/protocol.privnet-python.json:/neo-python/neo/data/protocol.privnet.json
    ports:
      - 30342:20332