version: "3"
services:
  neo-scan-openwallet:
    image: slipoh/neo-scan
    hostname: neo-scan-openwallet
    ports:
      - 4000:4000
    links:
      - postgresql:postgres
      - neo-privnet:20333
      - neo-privnet:20334
      - neo-privnet:20335
      - neo-privnet:20336
      - neo-privnet:20337
      - neo-privnet:30333
      - neo-privnet:30334
      - neo-privnet:30335
      - neo-privnet:30336
      - neo-privnet:30337
    depends_on:
      - postgresql
      - neo-privnet
  postgresql:
    image: postgres:10.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  neo-privnet:
    image: axlabs/neo-privatenet-openwallet-docker:latest
    hostname: neo-privnet
    ports:
      - 20333:20333
      - 20334:20334
      - 20335:20335
      - 20336:20336
      - 20337:20337
      - 30333:30333
      - 30334:30334
      - 30335:30335
      - 30336:30336
      - 30337:30337